baseURL = "https://fluffyroom.on-fleek.app/"
languageCode = "pl"
title = "Fluffyroom of Kotuni"
theme = "hugo-theme-codex"  # Jeśli używasz motywu

[params]
  description = "Fluffyroom for Sliczny Kotuni."

[outputFormats]
    [outputFormats.HTML]
        mediaType = "text/html"
        isPlainText = false
        notAlternative = true

[outputs]
    home = ["HTML"]
    page = ["HTML"]