baseURL = "https://fluffyroom.on-fleek.app/"
languageCode = "pl"
title = "Fluffyroom of Kotuni"
theme = "hugo-theme-codex"  # Jeśli używasz motywu

[params]
  description = "Fluffyroom for Sliczny Kotuni."

[module]
  [[module.mounts]]
    source = "static"
    target = "static"

[outputs]
  home = ["HTML"]