baseURL = "https://fluffyroom.on-fleek.app/"
languageCode = "pl"
title = "Śliczny Kotuni - Fluffyroom"
theme = "hugo-theme-codex"

[params]
  description = "Profesjonalne kocie zdjęcia."\

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]